import React,{useCallback,useState}from'react';
import{View,Text,ScrollView,Pressable,StyleSheet,ActivityIndicator,RefreshControl}from'react-native';
import{router,useFocusEffect}from'expo-router';import{Ionicons}from'@expo/vector-icons';import H from'../components/ClubHeader';import{api}from'../src/api';import{useAuth}from'../src/AuthContext';import{C,card,sectionTitle}from'../src/theme';
export default function Communications(){const{signedIn}=useAuth();const[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState('');
const load=async()=>{try{setError('');setRows(await api('/communications')||[])}catch(e){setError(e.message)}finally{setLoading(false);setRefreshing(false)}};
useFocusEffect(useCallback(()=>{if(signedIn)load();else setLoading(false)},[signedIn]));
const toggle=async(r)=>{const enabled=!r.subscribed;setRows(x=>x.map(y=>y.id===r.id?{...y,subscribed:enabled}:y));try{await api('/communications/'+r.id+'/notifications',{method:'POST',body:JSON.stringify({enabled})})}catch(e){setRows(x=>x.map(y=>y.id===r.id?{...y,subscribed:!enabled}:y));}};
return <View style={s.fill}><H app={{name:'University Park Lions'}}/><ScrollView contentContainerStyle={s.w} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}}/>}><Text style={s.h}>Discussion Rooms</Text><Text style={s.sub}>Club conversations, motions and voting.</Text>{!signedIn?<View style={s.notice}><Ionicons name="lock-closed-outline" size={25} color={C.blue}/><Text style={s.noticeText}>Sign in to participate in club discussions.</Text><Pressable style={s.primary} onPress={()=>router.push('/login')}><Text style={s.primaryText}>Member Sign In</Text></Pressable></View>:loading?<ActivityIndicator color={C.blue}/>:error?<Text style={s.err}>{error}</Text>:rows.length===0?<Text style={s.empty}>No discussion rooms are available.</Text>:rows.map(r=><Pressable key={r.id} style={s.room} onPress={()=>router.push('/discussion/'+r.id)}><View style={s.top}><View style={s.icon}><Ionicons name={r.pinned?'pin':'chatbubbles-outline'} size={21} color={C.blue}/></View><View style={{flex:1}}><Text style={s.title}>{r.title}</Text>{r.description?<Text style={s.desc} numberOfLines={2}>{r.description}</Text>:null}</View><Pressable hitSlop={12} style={s.bell} onPress={e=>{e.stopPropagation?.();toggle(r)}}><Ionicons name={r.subscribed?'notifications':'notifications-outline'} size={22} color={r.subscribed?C.gold:C.muted}/></Pressable><Ionicons name="chevron-forward" size={20} color={C.muted}/></View>{r.latest?<Text style={s.latest} numberOfLines={2}><Text style={{fontWeight:'800'}}>{r.latest.author}: </Text>{r.latest.content}</Text>:<Text style={s.latest}>No posts yet.</Text>}</Pressable>)}</ScrollView></View>}
const s=StyleSheet.create({fill:{flex:1,backgroundColor:C.bg},w:{padding:16,paddingBottom:34},h:{...sectionTitle,fontSize:26},sub:{color:C.muted,marginTop:3,marginBottom:14},room:{...card,padding:14,marginBottom:12},top:{flexDirection:'row',alignItems:'center',gap:10},icon:{width:42,height:42,borderRadius:21,backgroundColor:C.softBlue,alignItems:'center',justifyContent:'center'},title:{fontSize:16,fontWeight:'900',color:C.navy},desc:{fontSize:12,color:C.muted,marginTop:2},latest:{fontSize:12,color:C.text,marginTop:12,paddingTop:10,borderTopWidth:1,borderColor:C.line},bell:{padding:6},notice:{...card,padding:20,alignItems:'center'},noticeText:{color:C.text,textAlign:'center',marginVertical:10},primary:{backgroundColor:C.gold,paddingVertical:11,paddingHorizontal:18,borderRadius:10},primaryText:{fontWeight:'900',color:C.navy},err:{color:C.danger},empty:{color:C.muted,textAlign:'center',padding:24}});
